[game]
hostname = "🌟 Corvax — Вега SandBox 🌟[18+]"
desc = "Корвакс — первый русскоязычный проект в Space Station 14.\nВега — это первый официальный ЕРП сервер от Корвакс!\nЕРП является лишь допустимой опцией, а не заменяющей частью геймплея."
map_pool = "WegaDefaultMapPool"
fallbackpreset = "sandbox"
maxplayers = 60
soft_max_players = 40
map_rotation = false

[net]
tickrate = 30

[netres]
limit = 25.0

[viewport]
maximum_width = 26

[admin]
admins_count_in_playercount = true

[movement]
mob_pushing = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 99999
min_overall_minutes = 0

[hub]
advertise = false
tags = "lang:ru,rp:low,rp:med,region:eu_e,18+"

[server]
lobby_name = "🌟 Corvax — Вега SandBox 🌟[18+]"

[shuttle]
arrivals_map = "/Maps/Corvax/Misc/corvax_terminal.yml"
