[game]
hostname = "🌟 Corvax — Вега 🌟[18+]"
desc = "Корвакс — первый русскоязычный проект в Space Station 14.\nЗдесь помогут новичкам!\nНа этом сервере пониженные требования к RP."
map_pool = "CorvaxDefaultMapPool"
maxplayers = 180
soft_max_players = 100
map_rotation = true

[wega]
respawn_enabled = true

[net]
tickrate = 30

[netres]
limit = 25.0

[infolinks]
#discord = "https://discord.ss14.ru"
wiki = "https://station14.ru"
#appeal = "https://discord.ss14.ru"
website = "https://ss14.ru"

[viewport]
maximum_width = 26

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_minutes = 0
deny_vpn = true
enable_without_admins = true
disable_with_admins = true

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:low,rp:med,region:eu_e,18+"

[server]
rules_file = "WegaRuleset"

[atmos]
max_explosion_range = 5
