- type: gameMapPool
  id: WegaDefaultMapPool
  maps:
  # Highpop
  - WegaKerberos
  - #CorvaxAvrite
  - WegaCyberiad
  - WegaCereStation
  # Midpop
  - CorvaxPaper
  - Core
  - Bagel
  - Marathon
  # Lowpop
  - CorvaxSilly
  - Barratry
  - Packed
  - Meta
