- type: gameMapPool
  id: WegaDefaultMapPool
  maps:
  # Highpop
  - WegaKerberos
  - WegaCyberiad
  - WegaCereStation
  - WegaSpectrum
  - WegaEmerald
  - Fland
  # Midpop
  - CorvaxPaper
  - Core
  - Bagel
  - Marathon
  # Lowpop
  - CorvaxSilly
  - WegaMaus
  - Barratry
  - Packed
  - Meta
