- type: job
  id: Surgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 48000
  startingGear: SurgeonGear
  icon: "JobIconSurgeon"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Cryogenics

- type: startingGear
  id: SurgeonGear
  equipment:
    id: SurgeonPDA
    ears: ClothingHeadsetMedical
    gloves: ClothingHandsGlovesLatexSurgeon
    belt: SuperSurgerykitFilled
