# Evil Twin
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleEvilTwin
  name: Evil Twin Role
#  description: mind-role-evil-twin-description
  components:
  - type: MindRole
    antagPrototype: EvilTwin
    exclusiveAntag: true
    roleType: SoloAntagonist
  - type: EvilTwinRole

# Vampire
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleVampire
  name: Vampire Role
#  description: mind-role-vampire-description
  components:
  - type: MindRole
    antagPrototype: Vampire
    roleType: SoloAntagonist
  - type: VampireRole

# BloodCultist
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodCultist
  name: Blood Cultist Role
#  description: mind-role-vampire-description
  components:
  - type: MindRole
    antagPrototype: BloodCultist
    roleType: TeamAntagonist
  - type: BloodCultistRole
