- type: surgeryGraph
  id: BaseSurgery
  startNodes:
    - TorsoClosed
    - HeadClosed
    - AttachHead
    - AmputateLeftArm
    - AttachLeftArm
    - AmputateRightArm
    - AttachRightArm
    - AmputateLeftHand
    - AttachLeftHand
    - AmputateRightHand
    - AttachRightHand
    - AmputateLeftLeg
    - AttachLeftLeg
    - AmputateRightLeg
    - AttachRightLeg
    - AmputateLeftFoot
    - AttachLeftFoot
    - AmputateRightFoot
    - AttachRightFoot
